spring:
  datasource:
      url : jdbc:postgresql://localhost:5432/dlut?useUnicode=true&characterEncoding=UTF-8
      username : postgres
      password : 123456
  jpa:
    show-sql : true
    hibernate:
      ddl-auto : update

